definitions:
  database.FetchProductResult:
    properties:
      count:
        type: integer
      data:
        items:
          $ref: '#/definitions/model.Product'
        type: array
    type: object
  model.Product:
    properties:
      catId:
        type: integer
      countReview:
        type: integer
      discountPercentage:
        type: integer
      gaKey:
        type: string
      id:
        type: integer
      imageUrl:
        type: string
      imageUrlLarge:
        type: string
      name:
        type: string
      original_price:
        type: string
      preorder:
        type: boolean
      price:
        type: string
      priceInt:
        type: integer
      rating:
        type: number
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /product:
    get:
      parameters:
      - default: 1
        in: query
        name: page
        type: integer
      - default: 10
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.FetchProductResult'
            type: array
      summary: api untuk mendapatkan data list product
      tags:
      - product
  /product/{id}:
    get:
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
      summary: api untuk mendapatkan data product satuan
      tags:
      - product
swagger: "2.0"
